apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  labels:
    app.kubernetes.io/name: book-microservice
    app.kubernetes.io/component: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
