apiVersion: v1
kind: Service
metadata:
  name: springboot-ENVIRONMENT-svc-BUILD_NUMBER
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: springboot-app
    version: "BUILD_NUMBER"
