apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-microservice
  labels:
    app.kubernetes.io/name: book-microservice
    app.kubernetes.io/component: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
        app.kubernetes.io/name: book-microservice
        app.kubernetes.io/component: microservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: book-microservice
        app.kubernetes.io/component: microservice
    spec:
      containers:
        - name: springboot-app
          image: IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP