apiVersion: v1
kind: Service
metadata:
  name: springboot-svc
  labels:
    app.kubernetes.io/name: springboot-microservice
    app.kubernetes.io/component: microservice
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: springboot-microservice
    app.kubernetes.io/component: microservice