apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-ENVIRONMENT-BUILD_NUMBER
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
        version: "BUILD_NUMBER"
    spec:
      containers:
        - name: springboot-ENVIRONMENT-BUILD_NUMBER
          image: IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
